import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "/src/styles/globals.css";
import Navbar from "@/components/navbar";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home | Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uz">
      <body className={montserrat.className}>
        <Navbar />
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
